version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: missiondb-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: missiondb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mission-net

volumes:
  postgres_data:

networks:
  mission-net:
